openapi: 3.0.0
info:
  title: Ship Routing API
  description: Access the global ship routing service via a RESTful API
  version: 0.0.1

servers:
  - url: http://localhost:8081
    description: default server of the backend

paths:
  /routers:
    get:
      summary: Get a list of available routers
      responses:
        '200':
          description: List of available routers
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RouterList"
  /routers/{router}:
    post:
      summary: Compute a new route
      operationId: computeRoute
      requestBody:
        description: Define origin and destination of the route to be computed
        required: true
        content:
          application/json:
              schema: 
                $ref: "#/components/schemas/RouteRequest"
      responses:
        '200':
          description: Result of the route request
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/RouteResult"

components:
  schemas:
    RouterList:
      description: |
        List of routers
      type: array
      items:
        type: object
        properties:
          id:
            type: string
          name:
            type: string
        required:
          - id
          - name
    Point:
      description: |
        Object representation of a point in the Geographic Coordinate System (GCS).
      properties:
        lat:
          type: number
          description: unit degree
          minimum: -90
          maximum: 90
        lon:
          type: number
          description: unit degree
          minimum: -180
          maximum: 180
      required:
        - lat
        - lon
    RouteRequest:
      type: object
      description: |
        Request a route from a origin to a destination.
      properties:
        origin:
          $ref: "#/components/schemas/Point"
        destination:
          $ref: "#/components/schemas/Point"
      required:
        - origin
        - destination
    RouteResult:
      type: object
      properties:
        exists:
          type: boolean
          description: States whether a route from origin to destination exists
        path:
          $ref: "#/components/schemas/Path"
        time:
          description: Time required to compute the shortest path.
          type: number
          minimum: 0
        search_space:
          type: array
          description: |
            The search space is a list of points being ordered by the time a point (node) has been settled by the algorithm.
          items:
            $ref: "#/components/schemas/Point"
      required:
        - exists
        - time
    Path:
      type: object
      description: A path is described by sequence of points as well as its total length.
      properties:
        waypoints:
          type : array
          description: A path is an ordered list of points.
          items:
            $ref: "#/components/schemas/Point"
          minItems: 1
        length:
          description: unit meters
          type: integer
      required:
        - waypoints
        - length