openapi: 3.0.0
info:
  title: Ship Routing API
  description: Access the global ship routing service via a RESTful API
  version: 0.0.1

paths:
  /routes:
    post:
      summary: Compute a new route
      operationId: computeRoute
      requestBody:
        description: Define origin and destination of the route to be computed
        required: true
        content:
          application/json:
              schema: 
                $ref: "#/components/schemas/RouteRequest"
      responses:
        '200':
          description: Result of the route request
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/RouteResult"          
components:
  schemas:
    Point:
      description: |
        Object representation of a point in the Geographic Coordinate System (GCS).
      properties:
        lat:
          type: number
          description: unit degree
          minimum: -90.00000000001
          maximum: 90
        lon:
          type: number
          description: unit degree
          minimum: -180
          maximum: 180
      required:
        - lat
        - lon
    RouteRequest:
      type: object
      description: |
        Request a route from a origin to a destination.
      properties:
        origin:
          $ref: "#/components/schemas/Point"
        destination:
          $ref: "#/components/schemas/Point"
      required:
        - origin
        - destination
    RouteResult:
      type: object
      properties:
        origin:
          $ref: "#/components/schemas/Point"
        destination:
          $ref: "#/components/schemas/Point"
        reachable:
          type: boolean
          description: States whether a route from origin to destination exists
        path:
          $ref: "#/components/schemas/Path"
      required:
        - origin
        - destination
        - reachable
    Path:
      type: object
      description: A path is described by sequence of points as well as its total length.
      properties:
        waypoints:
          type : array
          description: A path is an ordered list of points.
          items:
            $ref: "#/components/schemas/Point"
          minItems: 1
        length:
          description: unit meters
          type: integer
      required:
        - waypoints
        - length