/*
 * Ship Routing API
 *
 * Access the global ship routing service via a RESTful API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_server

type Node struct {

	Lat float32 `json:"lat,omitempty"`

	Lon float32 `json:"lon,omitempty"`
}

// AssertNodeRequired checks if the required fields are not zero-ed
func AssertNodeRequired(obj Node) error {
	return nil
}

// AssertRecurseNodeRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Node (e.g. [][]Node), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseNodeRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aNode, ok := obj.(Node)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertNodeRequired(aNode)
	})
}
