/*
 * Ship Routing API
 *
 * Access the global ship routing service via a RESTful API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	server "github.com/dmholtz/osm-ship-routing/pkg/server/openapi_server"
)

const fileName = "graphs/ocean_equi_4.fmi"

func main() {
	log.Printf("Loading graph '%s' into memory", fileName)
	DefaultApiService := server.NewDefaultApiService(fileName)
	DefaultApiController := server.NewDefaultApiController(DefaultApiService)

	router := server.NewRouter(DefaultApiController)
	log.Printf("Server started @ http://localhost:8081")

	log.Fatal(http.ListenAndServe(":8081", router))
}
